=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

# Common files
require 'harbor2_legacy_client/api_client'
require 'harbor2_legacy_client/api_error'
require 'harbor2_legacy_client/version'
require 'harbor2_legacy_client/configuration'

# Models
require 'harbor2_legacy_client/models/action'
require 'harbor2_legacy_client/models/action_1'
require 'harbor2_legacy_client/models/admin_job_schedule'
require 'harbor2_legacy_client/models/admin_job_schedule_obj'
require 'harbor2_legacy_client/models/bad_request_formated_error'
require 'harbor2_legacy_client/models/bool_config_item'
require 'harbor2_legacy_client/models/cve_allowlist'
require 'harbor2_legacy_client/models/cve_allowlist_item'
require 'harbor2_legacy_client/models/chart_api_error'
require 'harbor2_legacy_client/models/chart_metadata'
require 'harbor2_legacy_client/models/chart_version'
require 'harbor2_legacy_client/models/component_health_status'
require 'harbor2_legacy_client/models/component_overview_entry'
require 'harbor2_legacy_client/models/configurations'
require 'harbor2_legacy_client/models/configurations_response'
require 'harbor2_legacy_client/models/configurations_scan_all_policy'
require 'harbor2_legacy_client/models/configurations_scan_all_policy_parameter'
require 'harbor2_legacy_client/models/conflict_formated_error'
require 'harbor2_legacy_client/models/email_server_setting'
require 'harbor2_legacy_client/models/endpoint'
require 'harbor2_legacy_client/models/event_type'
require 'harbor2_legacy_client/models/filter_style'
require 'harbor2_legacy_client/models/forbidden_chart_api_error'
require 'harbor2_legacy_client/models/gc_result'
require 'harbor2_legacy_client/models/general_info'
require 'harbor2_legacy_client/models/input_secret'
require 'harbor2_legacy_client/models/insufficient_storage_chart_api_error'
require 'harbor2_legacy_client/models/integer_config_item'
require 'harbor2_legacy_client/models/internal_chart_api_error'
require 'harbor2_legacy_client/models/is_default'
require 'harbor2_legacy_client/models/label'
require 'harbor2_legacy_client/models/labels'
require 'harbor2_legacy_client/models/ldap_conf'
require 'harbor2_legacy_client/models/ldap_failed_import_users'
require 'harbor2_legacy_client/models/ldap_import_users'
require 'harbor2_legacy_client/models/ldap_users'
require 'harbor2_legacy_client/models/namespace'
require 'harbor2_legacy_client/models/not_found_chart_api_error'
require 'harbor2_legacy_client/models/notify_type'
require 'harbor2_legacy_client/models/overall_health_status'
require 'harbor2_legacy_client/models/password'
require 'harbor2_legacy_client/models/permission'
require 'harbor2_legacy_client/models/ping_registry'
require 'harbor2_legacy_client/models/project'
require 'harbor2_legacy_client/models/project_member'
require 'harbor2_legacy_client/models/project_member_entity'
require 'harbor2_legacy_client/models/project_metadata'
require 'harbor2_legacy_client/models/project_req'
require 'harbor2_legacy_client/models/project_scanner'
require 'harbor2_legacy_client/models/project_summary'
require 'harbor2_legacy_client/models/project_summary_quota'
require 'harbor2_legacy_client/models/put_registry'
require 'harbor2_legacy_client/models/quota'
require 'harbor2_legacy_client/models/quota_ref_object'
require 'harbor2_legacy_client/models/quota_switcher'
require 'harbor2_legacy_client/models/quota_update_req'
require 'harbor2_legacy_client/models/registry'
require 'harbor2_legacy_client/models/registry_credential'
require 'harbor2_legacy_client/models/registry_info'
require 'harbor2_legacy_client/models/replication_execution'
require 'harbor2_legacy_client/models/replication_filter'
require 'harbor2_legacy_client/models/replication_policy'
require 'harbor2_legacy_client/models/replication_task'
require 'harbor2_legacy_client/models/replication_trigger'
require 'harbor2_legacy_client/models/resource_list'
require 'harbor2_legacy_client/models/retention_execution'
require 'harbor2_legacy_client/models/retention_execution_task'
require 'harbor2_legacy_client/models/retention_metadata'
require 'harbor2_legacy_client/models/retention_policy'
require 'harbor2_legacy_client/models/retention_policy_scope'
require 'harbor2_legacy_client/models/retention_rule'
require 'harbor2_legacy_client/models/retention_rule_metadata'
require 'harbor2_legacy_client/models/retention_rule_param_metadata'
require 'harbor2_legacy_client/models/retention_rule_trigger'
require 'harbor2_legacy_client/models/retention_selector'
require 'harbor2_legacy_client/models/retention_selector_metadata'
require 'harbor2_legacy_client/models/robot_account'
require 'harbor2_legacy_client/models/robot_account_access'
require 'harbor2_legacy_client/models/robot_account_create'
require 'harbor2_legacy_client/models/robot_account_post_rep'
require 'harbor2_legacy_client/models/robot_account_update'
require 'harbor2_legacy_client/models/role'
require 'harbor2_legacy_client/models/role_param'
require 'harbor2_legacy_client/models/role_request'
require 'harbor2_legacy_client/models/scanner'
require 'harbor2_legacy_client/models/scanner_adapter_metadata'
require 'harbor2_legacy_client/models/scanner_capability'
require 'harbor2_legacy_client/models/scanner_registration'
require 'harbor2_legacy_client/models/scanner_registration_req'
require 'harbor2_legacy_client/models/scanner_registration_settings'
require 'harbor2_legacy_client/models/search'
require 'harbor2_legacy_client/models/search_repository'
require 'harbor2_legacy_client/models/search_result'
require 'harbor2_legacy_client/models/statistic_map'
require 'harbor2_legacy_client/models/stats'
require 'harbor2_legacy_client/models/storage'
require 'harbor2_legacy_client/models/string_config_item'
require 'harbor2_legacy_client/models/supported_webhook_event_types'
require 'harbor2_legacy_client/models/sys_admin_flag'
require 'harbor2_legacy_client/models/system_info'
require 'harbor2_legacy_client/models/trigger_settings'
require 'harbor2_legacy_client/models/unauthorized_chart_api_error'
require 'harbor2_legacy_client/models/user'
require 'harbor2_legacy_client/models/user_entity'
require 'harbor2_legacy_client/models/user_group'
require 'harbor2_legacy_client/models/user_profile'
require 'harbor2_legacy_client/models/user_search'
require 'harbor2_legacy_client/models/webhook_job'
require 'harbor2_legacy_client/models/webhook_last_trigger'
require 'harbor2_legacy_client/models/webhook_policy'
require 'harbor2_legacy_client/models/webhook_target_object'

# APIs
require 'harbor2_legacy_client/api/chart_repository_api'
require 'harbor2_legacy_client/api/label_api'
require 'harbor2_legacy_client/api/products_api'
require 'harbor2_legacy_client/api/quota_api'
require 'harbor2_legacy_client/api/retention_api'
require 'harbor2_legacy_client/api/robot_account_api'
require 'harbor2_legacy_client/api/scan_api'
require 'harbor2_legacy_client/api/scanners_api'
require 'harbor2_legacy_client/api/system_api'

module Harbor2LegacyClient
  class << self
    # Customize default settings for the SDK using block.
    #   Harbor2LegacyClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
