=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.22

=end

# Common files
require 'harbor2_legacy_client/api_client'
require 'harbor2_legacy_client/api_error'
require 'harbor2_legacy_client/version'
require 'harbor2_legacy_client/configuration'

# Models
require 'harbor2_legacy_client/models/bad_request_formated_error'
require 'harbor2_legacy_client/models/chart_api_error'
require 'harbor2_legacy_client/models/chart_metadata'
require 'harbor2_legacy_client/models/chart_version'
require 'harbor2_legacy_client/models/component_overview_entry'
require 'harbor2_legacy_client/models/conflict_formated_error'
require 'harbor2_legacy_client/models/email_server_setting'
require 'harbor2_legacy_client/models/forbidden_chart_api_error'
require 'harbor2_legacy_client/models/insufficient_storage_chart_api_error'
require 'harbor2_legacy_client/models/internal_chart_api_error'
require 'harbor2_legacy_client/models/label'
require 'harbor2_legacy_client/models/labels'
require 'harbor2_legacy_client/models/namespace'
require 'harbor2_legacy_client/models/not_found_chart_api_error'
require 'harbor2_legacy_client/models/permission'
require 'harbor2_legacy_client/models/unauthorized_chart_api_error'

# APIs
require 'harbor2_legacy_client/api/chart_repository_api'
require 'harbor2_legacy_client/api/label_api'
require 'harbor2_legacy_client/api/products_api'

module Harbor2LegacyClient
  class << self
    # Customize default settings for the SDK using block.
    #   Harbor2LegacyClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
